### ISSUE TITLE
Have project if you are interested

### ISSUE THREAD

**Issue by quickstreamingmedia** [Jayapraveen/Drm-Dash-stream-downloader#3]
Pm me

**Comment by quickstreamingmedia** [comment]
Can you make code seek to live dynamic playlist

**Comment by Jayapraveen** [comment]
Live media by default start in present time. Based on the implementation you can probably only rewind or start playback in present. If the usecase is really urgent you can send me a mail at xp3vq4rn4@relay.firefox.com with the work needed , the work already done, corresponding resource information and the way to contact you back.

**Comment by quickstreamingmedia** [comment]
you were not responding to mails lol i have been waiting since 2 days
