### ISSUE TITLE
implement code

### ISSUE THREAD

**Issue by yolanda123a** [Jayapraveen/Drm-Dash-stream-downloader#4]
is this the correct way to use this

python ./dashdownloader.py https:_______.mpd -o. -d

becasue this way dont download for me
thanks

**Comment by erickyun** [comment]
> is this the correct way to use this
> 
> python ./dashdownloader.py https:_______.mpd -o. -d
> 
> becasue this way dont download for me
> thanks

try without writing python like this
```
.\dashdownloader.py https:_______.mpd -o. -d
```

and where do you write the KEY and KİD?

**Comment by Jayapraveen** [comment]
You'll have to edit the script and set the manifest url. Rerun without any command line args.
