### ISSUE TITLE
[KeyError] Key not found

### ISSUE THREAD

**Issue by hdhilip98** [Jayapraveen/Drm-Dash-stream-downloader#7]
```
def decrypt(filename,keyid,video_title):
    try:
        key = keyfile[keyid]
        print(key)
        os.system(f"ffmpeg -y -decryption_key {key} -i {filename} -codec copy -metadata title={video_title} dec_{filename}")
    except KeyError as error:
        print("Key not found")
        exit()
```

The above function tries to fetch the decryption key from the "keyfile.json" file with the Key ID. 

Where do we get the decryption key?

**Comment by sorrowfan** [comment]
> ```
> def decrypt(filename,keyid,video_title):
>     try:
>         key = keyfile[keyid]
>         print(key)
>         os.system(f"ffmpeg -y -decryption_key {key} -i {filename} -codec copy -metadata title={video_title} dec_{filename}")
>     except KeyError as error:
>         print("Key not found")
>         exit()
> ```
> 
> The above function tries to fetch the decryption key from the "keyfile.json" file with the Key ID.
> 
> Where do we get the decryption key?

May be I can help you with that. How can I contact you?

**Comment by adam-saudagar** [comment]
did you find out how to do that?
